\c mosip_archive
\ir ddl/archive-audit-app_audit_log.sql
\ir ddl/archive-credential-batch_job_execution.sql
\ir ddl/archive-credential-batch_job_execution_context.sql
\ir ddl/archive-credential-batch_job_execution_params.sql
\ir ddl/archive-credential-batch_job_instance.sql
\ir ddl/archive-credential-batch_step_execution.sql
\ir ddl/archive-credential-batch_step_execution_context.sql
\ir ddl/archive-ida-credential_event_store.sql
\ir ddl/archive-credential-credential_transaction.sql
\ir ddl/archive-esignet-consent_history.sql
\ir ddl/archive-ida-anonymous_profile.sql
\ir ddl/archive-ida-auth_transaction.sql
\ir ddl/archive-ida-batch_job_execution_context.sql
\ir ddl/archive-ida-batch_job_execution_params.sql
\ir ddl/archive-ida-batch_job_execution.sql
\ir ddl/archive-ida-batch_job_instance.sql
\ir ddl/archive-ida-batch_step_execution_context.sql
\ir ddl/archive-ida-batch_step_execution.sql
\ir ddl/archive-ida-otp_transaction.sql
\ir ddl/archive-idrepo-anonymous_profile.sql
\ir ddl/archive-idrepo-credential_request_status.sql
\ir ddl/archive-idrepo-uin_draft.sql
\ir ddl/archive-kernel-otp_transaction.sql
\ir ddl/archive-master-bulkupload_transaction.sql
\ir ddl/archive-master-device_master_h.sql
\ir ddl/archive-master-machine_master_h.sql
\ir ddl/archive-master-registration_center_h.sql
\ir ddl/archive-master-user_detail_h.sql
\ir ddl/archive-master-zone_user_h.sql
\ir ddl/archive-pms-auth_policy_h.sql
\ir ddl/archive-pms-partner_h.sql
\ir ddl/archive-pms-secure_biometric_interface_h.sql
\ir ddl/archive-prereg-otp_transaction.sql
\ir ddl/archive-resident_grievance_ticket.sql
\ir ddl/archive-resident-otp_transaction.sql
\ir ddl/archive-resident_session.sql
\ir ddl/archive-resident_transaction.sql
\ir ddl/archive-resident_user_actions.sql
\ir ddl/archive-regprc-reg_demo_dedupe_list.sql
\ir ddl/archive-regprc-registration_transaction.sql
\ir ddl/archive-regprc-abis_response_det.sql
\ir ddl/archive-regprc-abis_response.sql
\ir ddl/archive-regprc-abis_request.sql
