\c mosip_archive 

GRANT CONNECT
   ON DATABASE mosip_archive
   TO archiveuser;

GRANT USAGE
   ON SCHEMA archive
   TO archiveuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA archive
   TO archiveuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA archive 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO archiveuser;

